//! Thread persistence on the `threads` table (A1-02, tech-spec §2 DDL).
//!
//! This module is the pure SQL layer: functions take scalar parameters (the
//! DDL strings for `mode`/`status`) and return plain row values, so
//! `vega_store` keeps no dependency back on `vega_conversation` (tech-spec
//! §1 dependency direction). The orchestration layer in
//! `vega_conversation::threads` owns the shared `Thread` struct, ulid id
//! generation, and the enum ↔ DDL-string bridging.

use rusqlite::{Connection, OptionalExtension, params};

/// The `SELECT` column list shared by the row-loading queries.
const COLUMNS: &str = "id, project_id, title, mode, permission_mode, model, \
                       status, pinned, unread, created_at, updated_at";

/// A raw `threads` row, field-for-field with the DDL.
///
/// `mode`/`status` stay DDL strings; parsing into the shared enums happens
/// one layer up in `vega_conversation`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ThreadRow {
    /// Primary key (ulid).
    pub id: String,
    /// Owning project id (`projects.id`).
    pub project_id: String,
    /// Display title.
    pub title: String,
    /// Run mode DDL string (`ask|plan|execute`).
    pub mode: String,
    /// Permission mode DDL string (`readonly|confirm|auto`).
    pub permission_mode: String,
    /// Model id.
    pub model: String,
    /// Lifecycle status DDL string (`active|archived`).
    pub status: String,
    /// Pinned flag (DDL integer 0/1).
    pub pinned: bool,
    /// Unread flag (DDL integer 0/1).
    pub unread: bool,
    /// Creation timestamp, unix milliseconds.
    pub created_at: i64,
    /// Last-activity timestamp, unix milliseconds.
    pub updated_at: i64,
}

/// Column values for a new `threads` row.
///
/// The id is minted by the caller (`vega_conversation`, T11 ruling: ulid
/// generation lives in the orchestration crate, not the SQL layer).
pub struct NewThread<'a> {
    /// Primary key (ulid) generated by the caller.
    pub id: &'a str,
    /// Owning project id; must reference an existing `projects` row (DDL
    /// foreign key).
    pub project_id: &'a str,
    /// Display title.
    pub title: &'a str,
    /// Run mode DDL string.
    pub mode: &'a str,
    /// Permission mode DDL string.
    pub permission_mode: &'a str,
    /// Model id.
    pub model: &'a str,
    /// Lifecycle status DDL string.
    pub status: &'a str,
    /// Pinned flag.
    pub pinned: bool,
    /// Unread flag.
    pub unread: bool,
    /// Creation timestamp, unix milliseconds.
    pub created_at: i64,
    /// Last-activity timestamp, unix milliseconds.
    pub updated_at: i64,
}

/// Inserts a new thread row.
pub fn create(conn: &Connection, thread: NewThread) -> Result<(), rusqlite::Error> {
    conn.execute(
        "INSERT INTO threads (id, project_id, title, mode, permission_mode, model, \
         status, pinned, unread, created_at, updated_at) \
         VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11)",
        params![
            thread.id,
            thread.project_id,
            thread.title,
            thread.mode,
            thread.permission_mode,
            thread.model,
            thread.status,
            thread.pinned,
            thread.unread,
            thread.created_at,
            thread.updated_at,
        ],
    )?;
    Ok(())
}

/// Lists the threads of one project: the pinned group first, then most
/// recently updated (ui-spec §4.1: 置顶组优先；`idx_threads_project`
/// DDL index ordering covers the `updated_at DESC` part).
///
/// T13 (A1-05) adds the lifecycle filter: `Some("active")`/`Some("archived")`
/// restricts the list to that status; `None` keeps every row. The sidebar
/// main list reads active threads only and the 「已归档」 collapsed section
/// reads archived ones.
pub fn list_by_project(
    conn: &Connection,
    project_id: &str,
    status: Option<&str>,
) -> Result<Vec<ThreadRow>, rusqlite::Error> {
    let rows = match status {
        Some(status) => {
            let mut stmt = conn.prepare(&format!(
                "SELECT {COLUMNS} FROM threads WHERE project_id = ?1 AND status = ?2 \
                 ORDER BY pinned DESC, updated_at DESC"
            ))?;
            stmt.query_map(params![project_id, status], thread_from_row)?
                .collect::<Result<Vec<_>, _>>()?
        }
        None => {
            let mut stmt = conn.prepare(&format!(
                "SELECT {COLUMNS} FROM threads WHERE project_id = ?1 \
                 ORDER BY pinned DESC, updated_at DESC"
            ))?;
            stmt.query_map([project_id], thread_from_row)?
                .collect::<Result<Vec<_>, _>>()?
        }
    };
    Ok(rows)
}

/// Renames one thread and bumps `updated_at` to `now` (A1-05: 按 DDL 语义
/// 重命名即会话活动，时间戳同步推进，使列表按最近更新排序).
///
/// Returns the number of rows updated; 0 means the thread does not exist.
pub fn rename(
    conn: &Connection,
    id: &str,
    title: &str,
    now: i64,
) -> Result<usize, rusqlite::Error> {
    conn.execute(
        "UPDATE threads SET title = ?1, updated_at = ?2 WHERE id = ?3",
        params![title, now, id],
    )
}

/// Sets the lifecycle status (`active` ↔ `archived`); `updated_at` is left
/// untouched so archiving does not reorder the list (A1-05).
///
/// Returns the number of rows updated; 0 means the thread does not exist.
pub fn set_status(conn: &Connection, id: &str, status: &str) -> Result<usize, rusqlite::Error> {
    conn.execute(
        "UPDATE threads SET status = ?1 WHERE id = ?2",
        params![status, id],
    )
}

/// Sets the pinned flag (0 ↔ 1); `updated_at` is left untouched (A1-05).
///
/// Returns the number of rows updated; 0 means the thread does not exist.
pub fn set_pinned(conn: &Connection, id: &str, pinned: bool) -> Result<usize, rusqlite::Error> {
    conn.execute(
        "UPDATE threads SET pinned = ?1 WHERE id = ?2",
        params![pinned, id],
    )
}

/// Deletes one thread and — in the same transaction — all of its `messages`
/// and `tool_calls` rows (A1-05: the DDL declares no `ON DELETE CASCADE`, so
/// the deletion must sweep child tables itself to prevent orphan rows).
///
/// `token_usage` rows are intentionally **kept**: they carry the cost audit
/// trail (成本审计) and must survive thread deletion.
///
/// Returns the number of threads deleted; 0 means the thread did not exist
/// (the transaction still commits, having touched nothing).
pub fn delete_thread(conn: &Connection, id: &str) -> Result<usize, rusqlite::Error> {
    let tx = conn.unchecked_transaction()?;
    tx.execute("DELETE FROM messages WHERE thread_id = ?1", [id])?;
    tx.execute("DELETE FROM tool_calls WHERE thread_id = ?1", [id])?;
    let deleted = tx.execute("DELETE FROM threads WHERE id = ?1", [id])?;
    tx.commit()?;
    Ok(deleted)
}

/// Loads one thread row; `Ok(None)` when the id does not exist.
pub fn find(conn: &Connection, id: &str) -> Result<Option<ThreadRow>, rusqlite::Error> {
    conn.query_row(
        &format!("SELECT {COLUMNS} FROM threads WHERE id = ?1"),
        [id],
        thread_from_row,
    )
    .optional()
}

/// Applies a partial update to one thread; `None` leaves the column
/// untouched and an all-`None` update is a no-op.
///
/// Returns the number of rows updated; 0 means either no matching row or a
/// no-op update (the caller distinguishes before calling when it needs to
/// report a missing thread).
pub fn update(
    conn: &Connection,
    id: &str,
    title: Option<&str>,
    status: Option<&str>,
    pinned: Option<bool>,
    unread: Option<bool>,
) -> Result<usize, rusqlite::Error> {
    let mut clauses: Vec<&'static str> = Vec::new();
    let mut values: Vec<Box<dyn rusqlite::ToSql>> = Vec::new();
    if let Some(value) = title {
        clauses.push("title = ?");
        values.push(Box::new(value.to_string()));
    }
    if let Some(value) = status {
        clauses.push("status = ?");
        values.push(Box::new(value.to_string()));
    }
    if let Some(value) = pinned {
        clauses.push("pinned = ?");
        values.push(Box::new(value));
    }
    if let Some(value) = unread {
        clauses.push("unread = ?");
        values.push(Box::new(value));
    }
    if clauses.is_empty() {
        return Ok(0);
    }
    values.push(Box::new(id.to_string()));
    let sql = format!("UPDATE threads SET {} WHERE id = ?", clauses.join(", "));
    conn.execute(
        &sql,
        rusqlite::params_from_iter(values.iter().map(|v| v.as_ref())),
    )
}

/// Open-thread touch semantics (A1-02): bumps `threads.updated_at` and the
/// owning `projects.last_opened_at` to `now` in a single transaction, so a
/// crash between the two writes cannot leave them inconsistent.
///
/// Returns the refreshed row; `Ok(None)` when the thread does not exist
/// (nothing is written).
pub fn open_thread(
    conn: &Connection,
    id: &str,
    now: i64,
) -> Result<Option<ThreadRow>, rusqlite::Error> {
    let tx = conn.unchecked_transaction()?;
    let updated = tx.execute(
        "UPDATE threads SET updated_at = ?1 WHERE id = ?2",
        params![now, id],
    )?;
    if updated == 0 {
        // 事务 drop 即回滚；线程不存在时未写任何行。
        return Ok(None);
    }
    tx.execute(
        "UPDATE projects SET last_opened_at = ?1 \
         WHERE id = (SELECT project_id FROM threads WHERE id = ?2)",
        params![now, id],
    )?;
    tx.commit()?;
    find(conn, id)
}

/// Maps one `threads` row into [`ThreadRow`].
fn thread_from_row(row: &rusqlite::Row) -> rusqlite::Result<ThreadRow> {
    Ok(ThreadRow {
        id: row.get(0)?,
        project_id: row.get(1)?,
        title: row.get(2)?,
        mode: row.get(3)?,
        permission_mode: row.get(4)?,
        model: row.get(5)?,
        status: row.get(6)?,
        pinned: row.get(7)?,
        unread: row.get(8)?,
        created_at: row.get(9)?,
        updated_at: row.get(10)?,
    })
}

#[cfg(test)]
mod tests {
    use super::ThreadRow;
    use crate::Store;
    use rusqlite::{Connection, params};
    use tempfile::tempdir;

    /// Creates a migrated store backed by a fresh temporary directory.
    fn open_store() -> (Store, tempfile::TempDir) {
        let dir = tempdir().unwrap();
        let store = Store::open(dir.path().join("vega.db")).unwrap();
        store.migrate().unwrap();
        (store, dir)
    }

    /// T11 裁决：测试所需 project 行用裸 SQL 插入（补齐 DDL 必填字段），
    /// 不依赖 T10 的函数。
    fn insert_project(conn: &Connection, id: &str, name: &str, opened_at: i64) {
        conn.execute(
            "INSERT INTO projects (id, path, name, git_default_branch, created_at, last_opened_at) \
             VALUES (?1, ?2, ?3, NULL, ?4, ?5)",
            params![id, format!("/tmp/{id}"), name, opened_at, opened_at],
        )
        .unwrap();
    }

    fn sample_row(id: &str, project_id: &str, updated_at: i64) -> ThreadRow {
        ThreadRow {
            id: id.to_string(),
            project_id: project_id.to_string(),
            title: String::new(),
            mode: "execute".to_string(),
            permission_mode: "confirm".to_string(),
            model: String::new(),
            status: "active".to_string(),
            pinned: false,
            unread: false,
            created_at: 1_000,
            updated_at,
        }
    }

    fn insert_row(conn: &Connection, row: &ThreadRow) {
        conn.execute(
            "INSERT INTO threads (id, project_id, title, mode, permission_mode, model, \
             status, pinned, unread, created_at, updated_at) \
             VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11)",
            params![
                row.id,
                row.project_id,
                row.title,
                row.mode,
                row.permission_mode,
                row.model,
                row.status,
                row.pinned as i64,
                row.unread as i64,
                row.created_at,
                row.updated_at,
            ],
        )
        .unwrap();
    }

    #[test]
    fn create_inserts_the_row_verbatim() {
        let (store, _dir) = open_store();
        insert_project(store.conn(), "p1", "alpha", 10);
        let row = sample_row("t1", "p1", 100);
        super::create(
            store.conn(),
            super::NewThread {
                id: &row.id,
                project_id: &row.project_id,
                title: &row.title,
                mode: &row.mode,
                permission_mode: &row.permission_mode,
                model: &row.model,
                status: &row.status,
                pinned: row.pinned,
                unread: row.unread,
                created_at: row.created_at,
                updated_at: row.updated_at,
            },
        )
        .unwrap();
        assert_eq!(super::find(store.conn(), "t1").unwrap(), Some(row));
    }

    #[test]
    fn create_rejects_unknown_project_via_foreign_key() {
        let (store, _dir) = open_store();
        let row = sample_row("t1", "missing", 100);
        let err = super::create(
            store.conn(),
            super::NewThread {
                id: &row.id,
                project_id: &row.project_id,
                title: &row.title,
                mode: &row.mode,
                permission_mode: &row.permission_mode,
                model: &row.model,
                status: &row.status,
                pinned: row.pinned,
                unread: row.unread,
                created_at: row.created_at,
                updated_at: row.updated_at,
            },
        )
        .unwrap_err();
        assert!(matches!(
            err,
            rusqlite::Error::SqliteFailure(e, _)
                if e.code == rusqlite::ErrorCode::ConstraintViolation
        ));
    }

    #[test]
    fn list_by_project_orders_by_updated_at_desc() {
        let (store, _dir) = open_store();
        insert_project(store.conn(), "p1", "alpha", 10);
        insert_row(store.conn(), &sample_row("t-old", "p1", 100));
        insert_row(store.conn(), &sample_row("t-new", "p1", 300));
        insert_row(store.conn(), &sample_row("t-mid", "p1", 200));
        // 其他项目的线程不得混入。
        insert_project(store.conn(), "p2", "beta", 20);
        insert_row(store.conn(), &sample_row("t-other", "p2", 999));

        let ids: Vec<String> = super::list_by_project(store.conn(), "p1", None)
            .unwrap()
            .iter()
            .map(|r| r.id.clone())
            .collect();
        assert_eq!(ids, vec!["t-new", "t-mid", "t-old"]);
    }

    #[test]
    fn list_by_project_orders_pinned_group_first() {
        let (store, _dir) = open_store();
        insert_project(store.conn(), "p1", "alpha", 10);
        // 置顶组（组内 updated_at 倒序）：t-p1(300) > t-p2(200)。
        let mut pinned_new = sample_row("t-p1", "p1", 300);
        pinned_new.pinned = true;
        let mut pinned_old = sample_row("t-p2", "p1", 200);
        pinned_old.pinned = true;
        insert_row(store.conn(), &pinned_new);
        insert_row(store.conn(), &pinned_old);
        // 未置顶但 updated_at 更晚的线程仍排在置顶组之后。
        insert_row(store.conn(), &sample_row("t-plain", "p1", 400));

        let ids: Vec<String> = super::list_by_project(store.conn(), "p1", None)
            .unwrap()
            .iter()
            .map(|r| r.id.clone())
            .collect();
        assert_eq!(ids, vec!["t-p1", "t-p2", "t-plain"]);
    }

    #[test]
    fn list_by_project_filters_by_status() {
        let (store, _dir) = open_store();
        insert_project(store.conn(), "p1", "alpha", 10);
        insert_row(store.conn(), &sample_row("t-a1", "p1", 300));
        insert_row(store.conn(), &sample_row("t-a2", "p1", 100));
        let mut archived = sample_row("t-h1", "p1", 200);
        archived.status = "archived".to_string();
        let mut archived_pinned = sample_row("t-h2", "p1", 50);
        archived_pinned.status = "archived".to_string();
        archived_pinned.pinned = true;
        insert_row(store.conn(), &archived);
        insert_row(store.conn(), &archived_pinned);
        // 其他项目的线程不得混入任何过滤结果。
        insert_project(store.conn(), "p2", "beta", 20);
        insert_row(store.conn(), &sample_row("t-other", "p2", 999));

        let active: Vec<String> = super::list_by_project(store.conn(), "p1", Some("active"))
            .unwrap()
            .iter()
            .map(|r| r.id.clone())
            .collect();
        assert_eq!(active, vec!["t-a1", "t-a2"]);
        // 归档组同样置顶优先、updated_at 倒序。
        let archived_ids: Vec<String> =
            super::list_by_project(store.conn(), "p1", Some("archived"))
                .unwrap()
                .iter()
                .map(|r| r.id.clone())
                .collect();
        assert_eq!(archived_ids, vec!["t-h2", "t-h1"]);
        // None 不过滤。
        let all = super::list_by_project(store.conn(), "p1", None).unwrap();
        assert_eq!(all.len(), 4);
    }

    #[test]
    fn rename_updates_title_and_bumps_updated_at() {
        let (store, _dir) = open_store();
        insert_project(store.conn(), "p1", "alpha", 10);
        insert_row(store.conn(), &sample_row("t1", "p1", 100));

        assert_eq!(super::rename(store.conn(), "t1", "新标题", 900).unwrap(), 1);
        let row = super::find(store.conn(), "t1").unwrap().unwrap();
        assert_eq!(row.title, "新标题");
        assert_eq!(row.updated_at, 900);
        // 其余列不受影响。
        assert_eq!(row.status, "active");
        assert!(!row.pinned);
    }

    #[test]
    fn rename_missing_thread_updates_nothing() {
        let (store, _dir) = open_store();
        assert_eq!(super::rename(store.conn(), "missing", "x", 900).unwrap(), 0);
    }

    #[test]
    fn set_status_and_set_pinned_keep_updated_at() {
        let (store, _dir) = open_store();
        insert_project(store.conn(), "p1", "alpha", 10);
        insert_row(store.conn(), &sample_row("t1", "p1", 100));

        assert_eq!(
            super::set_status(store.conn(), "t1", "archived").unwrap(),
            1
        );
        assert_eq!(super::set_pinned(store.conn(), "t1", true).unwrap(), 1);
        let row = super::find(store.conn(), "t1").unwrap().unwrap();
        assert_eq!(row.status, "archived");
        assert!(row.pinned);
        // 状态/置顶切换不是会话活动：updated_at 保持原值。
        assert_eq!(row.updated_at, 100);
    }

    #[test]
    fn set_status_and_set_pinned_missing_thread_update_nothing() {
        let (store, _dir) = open_store();
        assert_eq!(
            super::set_status(store.conn(), "missing", "archived").unwrap(),
            0
        );
        assert_eq!(super::set_pinned(store.conn(), "missing", true).unwrap(), 0);
    }

    /// 裸 SQL 灌入 message / tool_call / token_usage 行（补齐 DDL 必填字段），
    /// 用于 delete_thread 的事务原子性验证（架构师裁决③）。
    fn insert_thread_children(conn: &Connection, thread_id: &str) {
        conn.execute(
            "INSERT INTO messages (id, thread_id, seq, role, content, created_at) \
             VALUES (?1, ?2, 1, 'user', 'hello', 1)",
            params![format!("m-{thread_id}"), thread_id],
        )
        .unwrap();
        conn.execute(
            "INSERT INTO tool_calls (id, thread_id, message_id, seq, tool, input_json, status, created_at) \
             VALUES (?1, ?2, ?3, 1, 'bash', '{}', 'success', 2)",
            params![format!("tc-{thread_id}"), thread_id, format!("m-{thread_id}")],
        )
        .unwrap();
        conn.execute(
            "INSERT INTO token_usage (thread_id, message_id, model, input_tokens, output_tokens, cost_microcents, created_at) \
             VALUES (?1, ?2, 'test-model', 10, 20, 3, 3)",
            params![thread_id, format!("m-{thread_id}")],
        )
        .unwrap();
    }

    fn count(conn: &Connection, table: &str, thread_id: &str) -> i64 {
        conn.query_row(
            &format!("SELECT COUNT(*) FROM {table} WHERE thread_id = ?1"),
            [thread_id],
            |row| row.get(0),
        )
        .unwrap()
    }

    #[test]
    fn delete_thread_removes_messages_and_tool_calls_in_one_transaction() {
        let (store, _dir) = open_store();
        insert_project(store.conn(), "p1", "alpha", 10);
        insert_row(store.conn(), &sample_row("t1", "p1", 100));
        insert_row(store.conn(), &sample_row("t2", "p1", 200));
        insert_thread_children(store.conn(), "t1");
        insert_thread_children(store.conn(), "t2");

        assert_eq!(super::delete_thread(store.conn(), "t1").unwrap(), 1);
        // thread 行与其 messages / tool_calls 一并消失（无孤儿行）。
        assert_eq!(super::find(store.conn(), "t1").unwrap(), None);
        assert_eq!(count(store.conn(), "messages", "t1"), 0);
        assert_eq!(count(store.conn(), "tool_calls", "t1"), 0);
        // token_usage 保留作成本审计（卡面要求）。
        assert_eq!(count(store.conn(), "token_usage", "t1"), 1);
        // 其他线程不受影响。
        assert!(super::find(store.conn(), "t2").unwrap().is_some());
        assert_eq!(count(store.conn(), "messages", "t2"), 1);
        assert_eq!(count(store.conn(), "tool_calls", "t2"), 1);
    }

    #[test]
    fn delete_thread_missing_thread_deletes_nothing() {
        let (store, _dir) = open_store();
        assert_eq!(super::delete_thread(store.conn(), "missing").unwrap(), 0);
    }

    #[test]
    fn update_touches_only_the_given_fields() {
        let (store, _dir) = open_store();
        insert_project(store.conn(), "p1", "alpha", 10);
        insert_row(store.conn(), &sample_row("t1", "p1", 100));

        let updated = super::update(
            store.conn(),
            "t1",
            Some("标题"),
            Some("archived"),
            Some(true),
            None,
        )
        .unwrap();
        assert_eq!(updated, 1);
        let row = super::find(store.conn(), "t1").unwrap().unwrap();
        assert_eq!(row.title, "标题");
        assert_eq!(row.status, "archived");
        assert!(row.pinned);
        // 未指定的列保持原值。
        assert!(!row.unread);
        assert_eq!(row.updated_at, 100);
    }

    #[test]
    fn update_all_none_is_a_noop() {
        let (store, _dir) = open_store();
        insert_project(store.conn(), "p1", "alpha", 10);
        insert_row(store.conn(), &sample_row("t1", "p1", 100));

        assert_eq!(
            super::update(store.conn(), "t1", None, None, None, None).unwrap(),
            0
        );
        assert_eq!(
            super::find(store.conn(), "t1").unwrap(),
            Some(sample_row("t1", "p1", 100))
        );
    }

    #[test]
    fn update_missing_thread_updates_nothing() {
        let (store, _dir) = open_store();
        assert_eq!(
            super::update(store.conn(), "missing", Some("x"), None, None, None).unwrap(),
            0
        );
    }

    #[test]
    fn open_thread_bumps_thread_and_project_together() {
        let (store, _dir) = open_store();
        insert_project(store.conn(), "p1", "alpha", 10);
        insert_row(store.conn(), &sample_row("t1", "p1", 100));

        let row = super::open_thread(store.conn(), "t1", 5_000)
            .unwrap()
            .unwrap();
        assert_eq!(row.updated_at, 5_000);
        let last_opened_at: i64 = store
            .conn()
            .query_row(
                "SELECT last_opened_at FROM projects WHERE id = 'p1'",
                [],
                |r| r.get(0),
            )
            .unwrap();
        // 单事务触碰：两个时间戳推进到同一个值。
        assert_eq!(last_opened_at, 5_000);
    }

    #[test]
    fn open_thread_missing_thread_writes_nothing() {
        let (store, _dir) = open_store();
        insert_project(store.conn(), "p1", "alpha", 10);
        assert!(
            super::open_thread(store.conn(), "missing", 5_000)
                .unwrap()
                .is_none()
        );
        let last_opened_at: i64 = store
            .conn()
            .query_row(
                "SELECT last_opened_at FROM projects WHERE id = 'p1'",
                [],
                |r| r.get(0),
            )
            .unwrap();
        assert_eq!(last_opened_at, 10);
    }
}
