use super::*;

/// Run mode of a thread (tech-spec §3 `RunMode`, A2-09): ask | plan | execute.
///
/// Stored as the lowercase DDL string in `threads.mode`

/// Run mode of a thread (tech-spec §3 `RunMode`, A2-09): ask | plan | execute.
///
/// Stored as the lowercase DDL string in `threads.mode`

/// (`TEXT NOT NULL DEFAULT 'execute'`).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ThreadMode {
    /// Ask mode: read-only question answering.
    Ask,
    /// Plan mode: propose a plan without executing it.
    Plan,
    /// Execute mode: run tools subject to the permission gate (DDL default).
    Execute,
}

impl ThreadMode {
    /// The DDL string for this mode.
    pub fn as_str(self) -> &'static str {
        match self {
            ThreadMode::Ask => "ask",
            ThreadMode::Plan => "plan",
            ThreadMode::Execute => "execute",
        }
    }

    /// Parses the DDL string; `None` for values outside `ask|plan|execute`.
    ///
    /// Named `parse` (not `from_str`) so the inherent method does not shadow
    /// `std::str::FromStr` (clippy `should_implement_trait`); the enum keeps
    /// `Option` semantics until an error type is warranted.
    pub fn parse(value: &str) -> Option<Self> {
        match value {
            "ask" => Some(ThreadMode::Ask),
            "plan" => Some(ThreadMode::Plan),
            "execute" => Some(ThreadMode::Execute),
            _ => None,
        }
    }
}

/// Lifecycle status of a thread: active | archived.
///
/// Stored as the lowercase DDL string in `threads.status`
/// (`TEXT NOT NULL DEFAULT 'active'`).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ThreadStatus {
    /// Live in the sidebar list (DDL default).
    Active,
    /// Hidden from the main list (T13 manages the archive).
    Archived,
}

impl ThreadStatus {
    /// The DDL string for this status.
    pub fn as_str(self) -> &'static str {
        match self {
            ThreadStatus::Active => "active",
            ThreadStatus::Archived => "archived",
        }
    }

    /// Parses the DDL string; `None` for values outside `active|archived`.
    ///
    /// Named `parse` for the same reason as [`ThreadMode::parse`].
    pub fn parse(value: &str) -> Option<Self> {
        match value {
            "active" => Some(ThreadStatus::Active),
            "archived" => Some(ThreadStatus::Archived),
            _ => None,
        }
    }
}

/// A conversation thread, aligned field-by-field with the `threads` DDL.
///
/// `permission_mode` is typed and fail-closed on create/load. `model` stays a
/// raw provider id string.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Thread {
    /// Primary key (ulid, generated by this crate on creation).
    pub id: String,
    /// Owning project id (`projects.id`, foreign key).
    pub project_id: String,
    /// Display title; empty until the user renames (T13).
    pub title: String,
    /// Run mode (`ask|plan|execute`).
    pub mode: ThreadMode,
    /// Permission mode (`readonly|confirm|auto`).
    pub permission_mode: PermissionMode,
    /// Model id; empty string until a provider is configured (S4).
    pub model: String,
    /// Lifecycle status (`active|archived`).
    pub status: ThreadStatus,
    /// Pinned to the top of its group (ordering is T12/T13).
    pub pinned: bool,
    /// Unread marker; stays 0 until streaming lands (S3).
    pub unread: bool,
    /// Creation timestamp, unix milliseconds.
    pub created_at: i64,
    /// Last-activity timestamp, unix milliseconds (bumped on open/touch).
    pub updated_at: i64,
}

/// Minimal projection of the project a thread attaches to.
///
/// T11 resolves the "current project" for thread creation; the full
/// project model belongs to T10/S3 and is not pre-defined here.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CurrentProject {
    /// Owning project id (`projects.id`).
    pub id: String,
    /// Display name.
    pub name: String,
}

/// Field set accepted by the thread update path
/// (`vega_conversation::threads::update_thread`, backed by
/// `vega_store::threads::update`).
///
/// `None` leaves a column untouched; `Some` overwrites it.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct ThreadUpdate {
    /// New title.
    pub title: Option<String>,
    /// New lifecycle status.
    pub status: Option<ThreadStatus>,
    /// New pinned flag.
    pub pinned: Option<bool>,
    /// New unread flag.
    pub unread: Option<bool>,
}

/// Persisted Plan review lifecycle.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PlanStatus {
    Pending,
    Approved,
    ChangesRequested,
    Abandoned,
}

impl PlanStatus {
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Pending => "pending",
            Self::Approved => "approved",
            Self::ChangesRequested => "changes_requested",
            Self::Abandoned => "abandoned",
        }
    }

    pub fn parse(value: &str) -> Option<Self> {
        match value {
            "pending" => Some(Self::Pending),
            "approved" => Some(Self::Approved),
            "changes_requested" => Some(Self::ChangesRequested),
            "abandoned" => Some(Self::Abandoned),
            _ => None,
        }
    }
}

/// Typed, fully validated Plan projection shared with the UI.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Plan {
    pub id: String,
    pub thread_id: String,
    pub content: String,
    pub status: PlanStatus,
    pub review_note: Option<String>,
    pub reviewed_at: Option<i64>,
}

/// A first-wins review command from the UI.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum PlanReviewAction {
    Approve,
    RequestChanges { note: Option<String> },
    Abandon { note: Option<String> },
}

/// Stable result of a conditional review transaction.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum PlanReviewOutcome {
    Applied {
        instruction_message_id: Option<String>,
    },
    Stale,
}

impl ThreadUpdate {
    /// Whether no field is set; the update is then a no-op.
    pub fn is_empty(&self) -> bool {
        self.title.is_none()
            && self.status.is_none()
            && self.pinned.is_none()
            && self.unread.is_none()
    }
}
